const data = [
  {
  id:1,
  risk_score: 0,
  nigerian_stock: "18%",
  foreign_stock: "4%",
  tech_stock: "2%",
  emerging_stock: "7%",
  nigerian_bonds: "35%",
  foreign_bonds: "15%",
  commodities: "7%",
  real_estate: "12%",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:2,
  risk_score: 1,
  nigerian_stock: "20%",
  foreign_stock: "5%",
  tech_stock: "3%",
  emerging_stock: "7%",
  nigerian_bonds: "35%",
  foreign_bonds: "6%",
  commodities: "12%",
  real_estate: "12%",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:3,
  risk_score: 2,
  nigerian_stock: "23%",
  foreign_stock: "5%",
  tech_stock: "4%",
  emerging_stock: "7%",
  nigerian_bonds: "35%",
  foreign_bonds: "14%",
  commodities: "12%",
  real_estate: "0%",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:4,
  risk_score: 3,
  nigerian_stock: "26%",
  foreign_stock: "6%",
  tech_stock: "4%",
  emerging_stock: "7%",
  nigerian_bonds: "35%",
  foreign_bonds: "10%",
  commodities: "12%",
  real_estate: "0",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:5,
  risk_score: 4,
  nigerian_stock: "29%",
  foreign_stock: "7%",
  tech_stock: "5%",
  emerging_stock: "6%",
  nigerian_bonds: "35%",
  foreign_bonds: "6%",
  commodities: "12%",
  real_estate: "0%",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:6,
  risk_score: 5,
  nigerian_stock: "31%",
  foreign_stock: "8%",
  tech_stock: "6%",
  emerging_stock: "5%",
  nigerian_bonds: "35%",
  foreign_bonds: "3%",
  commodities: "12%",
  real_estate: "0%",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:7,
  risk_score: 6,
  nigerian_stock: "35%",
  foreign_stock: "8%",
  tech_stock: "7%",
  emerging_stock: "3%",
  nigerian_bonds: "35%",
  foreign_bonds: "12%",
  commodities: "0%",
  real_estate: "0%",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:8,
  risk_score: 7,
  nigerian_stock: "45%",
  foreign_stock: "13%",
  tech_stock: "12%",
  emerging_stock: "7%",
  nigerian_bonds: "23%",
  foreign_bonds: "0%",
  commodities: "0%",
  real_estate: "0%",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:9,
  risk_score: 8,
  nigerian_stock: "45%",
  foreign_stock: "18%",
  tech_stock: "17%",
  emerging_stock: "11%",
  nigerian_bonds: "9%",
  foreign_bonds: "0%",
  commodities: "0%",
  real_estate: "0%",
  t_bills: "0%",
  alternative: "0%",
},
  {
  id:10,
  risk_score: 9,
  nigerian_stock: "45%",
  foreign_stock: "20%",
  tech_stock: "19%",
  emerging_stock: "14%",
  nigerian_bonds: "2%",
  foreign_bonds: "0%",
  commodities: "0%",
  real_estate: "0%",
  t_bills: "0%",
  alternative: "0%",
}
]


